pipeline: "svrtk"
docker: 
  cmd: " docker run <mount>
  fetalsvrtk/svrtk:general_auto_amd
  bash /home/auto-proc-svrtk/scripts/auto-brain-reconstruction.sh 
  <input_dir> <output_dir> 1 <input_tp> <output_res> 1"
singularity:
  cmd: null
path_to_output: "reo-SVR-output-brain.nii.gz"


