site_name: Fetpype 

theme:
  name: readthedocs
  logo: media/fetpype_logo.png  # Path to your logo file
  favicon: media/fetpype_favicon.png  # Path to your favicon file

plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          show_source: true
          members_order: source
          relative_crossrefs: true

        
- search
- autorefs
- awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
