brain_extraction:
  docker:
    image: "junshenxu/nesvor:latest "
    pre_command: "docker run --gpus=all "
  singularity:
    image: "/home/gmarti/SINGULARITY/nesvor_latest.sif "
    pre_command: "singularity exec --bind /gpfs:/gpfs --nv "